# Generated by Django 3.2.5 on 2021-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211001_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
